version: '2.124.2.{build}'
pull_requests:
  do_not_increment_build_number: true
init:
- ps: (new-object net.webclient).DownloadFile('https://dotnetcli.blob.core.windows.net/dotnet/beta/Installers/Latest/dotnet-dev-win-x64.latest.exe', "c:/dotnet-install.exe")
- ps: Start-Process c:\dotnet-install.exe -ArgumentList "/install","/quiet" -Wait
build_script:
- ps: dotnet restore
- ps: dotnet build Docker.DotNet Docker.DotNet.BasicAuth Docker.DotNet.X509
