name: CI

on:
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Build
      run: dotnet build -c Release
 
# temp disable while testing
#    - name: Test
#      run: dotnet test -c Release --no-build
              
    - name: Generate documentation
      uses: mattnotmitt/doxygen-action@v1
      with:
            working-directory: 'src/DockerSdk/'
            doxyfile-path: './Doxyfile'

      # TODO: this will actually be a release step
    - name: Publish documentation
      uses: Cecilapp/GitHub-Pages-deploy@3.1.0
      with:
            build_dir: src/DockerSdk/html/
